### ISSUE TITLE
Editing a card got into an unrecoverable state

### ISSUE THREAD

**Issue by mikethecanuck-cb** [the-webelos/retrospec-client#37]
I tried to edit a card, clicked a couple of times on the colour circles (I was trying to remove an assigned colour circle) and it appears the card "committed" in a state that can't be properly displayed.

here's the board where I got one in "blurry" state:
https://retrospec-server.qalab.local/?#/board/bccb0c8d-e1d6-4ccb-9442-b296a6dd9211

![screen shot 2019-01-16 at 11 47 28 am](https://user-images.githubusercontent.com/41172476/51274734-c865c100-1984-11e9-95e4-233cb29e59a4.png)

**Comment by jrhackett** [comment]
I believe this is fixed in caf25c8
